"""empty message

Revision ID: 763fa4ef1ee3
Revises: f4b9c444a093
Create Date: 2022-06-14 15:18:13.688861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763fa4ef1ee3'
down_revision = 'f4b9c444a093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
